### ISSUE TITLE
Cake task RunTests not pointing to correct dll path

### ISSUE THREAD

**Issue by josdeweger** [damianh/AwsLambdaOwin#2]
Was interested in the the way you setup your Cake tasks. I believe the RunTests Cake task is not pointing to the correct path:
```var dll = "./src/AwsLambdaOwin.Tests/bin/" + configuration + "/AwsLambdaOwin.Tests.dll";```

Shouldn't this be 
```var dll = "./src/AwsLambdaOwin.Tests/bin/" + configuration + "/netcoreapp1.1/AwsLambdaOwin.Tests.dll";``` ?

Then, when running .\build.ps1, I get 
```xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
System.InvalidOperationException: Unknown test framework: could not find xunit.dll (v1) or xunit.execution.*.dll (v2)

**Comment by damianh** [comment]
Repo'd; thanks for reporting.

Annoyingly I was getting this from CLI

![image](https://cloud.githubusercontent.com/assets/57436/26277293/fd8a579c-3d85-11e7-929f-df81391b53bc.png)

I'd have expected the script to fail. Will fix.

**Comment by damianh** [comment]
Looks like we're good https://ci.appveyor.com/project/damianh/awslambdaowin/build/41 

Sorry for delay; missed this.
